### ISSUE TITLE
Clicking existing reaction fires invalid XHR POST request

### ISSUE THREAD

**Issue by davwheat** [FriendsOfFlarum/reactions#28]
Clicking an existing reaction icon sends off a POST to the server with the payload `{ reaction: null }` instead of a valid reaction ID.

```js
{data: {type: "posts", id: "31", attributes: {reaction: null}}}
```

```html
<br />
<b>Notice</b>:  Trying to get property 'reaction' of non-object in <b>/var/www/vendor/fof/reactions/src/Listener/SaveReactionsToDatabase.php</b> on line <b>122</b><br />
<br />
<b>Fatal error</b>:  Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /var/www/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:24
Stack trace:
#0 /var/www/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent()
#1 /var/www/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;assertNoPreviousOutput()
#2 /var/www/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;emit()
#3 /var/www/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner-&gt;run()
#4 /var/www/public/index.php(26): Flarum\Http\Server-&gt;listen()
#5 {main}
  thrown in <b>/var/www/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php</b> on line <b>24</b><br />

```

**Comment by datitisev** [comment]
I've got a fix locally prepared for this, along with some improvements (regarding UI & backend). I'll try to release it today.

**Comment by datitisev** [comment]
Closed with https://github.com/FriendsOfFlarum/reactions/commit/f53b3d90522ce2889057c4374c150955d946df59.
