### ISSUE TITLE
BadMethodCallException: Method Illuminate\Support\Arr::_get does not exist

### ISSUE THREAD

**Issue by northeaster** [FriendsOfFlarum/reactions#34]
It gives an error while disabling emojis in the admin panel but it works fine when deleting emoji.

**/storage/logs**

```
[2020-11-06 09:17:35] flarum.ERROR: BadMethodCallException: Method Illuminate\Support\Arr::_get does not exist. in /var/www/html/flarum/vendor/illuminate/support/Traits/Macroable.php:77
Stack trace:
#0 /var/www/html/flarum/vendor/fof/reactions/src/Api/Controller/UpdateReactionController.php(48): Illuminate\Support\Arr::__callStatic()
#1 /var/www/html/flarum/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): FoF\Reactions\Api\Controller\UpdateReactionController->data()
#2 /var/www/html/flarum/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Api\Controller\AbstractSerializeController->handle()
#3 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#4 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process()
#5 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle()
#6 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#7 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(45): Laminas\Stratigility\Next->handle()
#8 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#9 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Laminas\Stratigility\Next->handle()
#10 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#11 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle()
#12 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#13 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle()
#14 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#15 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#16 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#17 /var/www/html/flarum/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#18 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process()
#19 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#20 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#21 /var/www/html/flarum/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#22 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#23 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#24 /var/www/html/flarum/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#25 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#26 /var/www/html/flarum/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle()
#27 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#28 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#29 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#30 /var/www/html/flarum/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle()
#31 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#32 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#33 /var/www/html/flarum/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#34 /var/www/html/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#35 /var/www/html/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#36 /var/www/html/flarum/index.php(26): Flarum\Http\Server->listen()
#37 {main}  
```

**php flarum info**
```
Flarum core 0.1.0-beta.14.1
PHP version: 7.4.12
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip
+---------------------------------+------------------+--------+
| Flarum Extensions               |                  |        |
+---------------------------------+------------------+--------+
| ID                              | Version          | Commit |
+---------------------------------+------------------+--------+
| flarum-approval                 | v0.1.0-beta.14   |        |
| flarum-bbcode                   | v0.1.0-beta.12   |        |
| flarum-emoji                    | v0.1.0-beta.14   |        |
| flarum-flags                    | v0.1.0-beta.14.1 |        |
| flarum-likes                    | v0.1.0-beta.14   |        |
| flarum-lock                     | v0.1.0-beta.14   |        |
| flarum-markdown                 | v0.1.0-beta.14   |        |
| flarum-mentions                 | v0.1.0-beta.14   |        |
| flarum-sticky                   | v0.1.0-beta.14   |        |
| flarum-subscriptions            | v0.1.0-beta.14   |        |
| flarum-suspend                  | v0.1.0-beta.14   |        |
| flarum-tags                     | v0.1.0-beta.14   |        |
| flarum-lang-english             | v0.1.0-beta.14.1 |        |
| flarum-statistics               | v0.1.0-beta.14   |        |
| fof-user-bio                    | 0.3.0            |        |
| tolgaaaltas-lang-turkish        | 0.14.1           |        |
| askvortsov-moderator-warnings   | v0.3.0           |        |
| v17development-seo              | 1.4              |        |
| fof-follow-tags                 | 0.5.0            |        |
| fof-formatting                  | 0.2.0            |        |
| fof-split                       | 0.5.0            |        |
| tolgaaaltas-turkish             | 0.14.0           |        |
| nearata-signup-confirm-password | v2.1.0           |        |
| fof-forum-statistics-widget     | 0.3.0            |        |
| nearata-copy-code-to-clipboard  | v1.1.0           |        |
| fof-drafts                      | 0.2.0            |        |
| fof-best-answer                 | 0.2.0            |        |
| fof-links                       | 0.4.0            |        |
| fof-linguist                    | 0.4.4            |        |
| fof-oauth                       | 0.1.0            |        |
| fof-terms                       | 0.5.0            |        |
| fof-merge-discussions           | 0.4.0            |        |
| fof-spamblock                   | 0.3.0            |        |
| fof-stopforumspam               | 0.3.1            |        |
| fof-geoip                       | 0.2.0            |        |
| fof-ban-ips                     | 0.3.0            |        |
| matteocontrini-imgur-upload     | v3.4.1           |        |
| fof-reactions                   | 0.4.1            |        |
+---------------------------------+------------------+--------+
Base URL: https://dursuncanpoyraz.com.tr/flarum
Installation path: /var/www/html/flarum
Debug mode: off
```

**Comment by karaok491** [comment]
Fixed `0.4.2`
